### ISSUE TITLE
An error was reported after the directory was deleted

### ISSUE THREAD

**Issue by cycle2zhou** [athityakumar/colorls#351]
### Description
After the directory in the terminal has been deleted, the ll command is used without any prompt or error, but with "colorls-la --sd --gs --group -- directories -- first" the following error is reported, as shown
![image](https://user-images.githubusercontent.com/33155330/79089572-31e7a180-7d79-11ea-8996-29fe9438252d.png)

The eos_platform_7.6_developer_edition_x64 directory in the path "~/Downloads/ eos_platform_7.6_developer_edition_x64" has been manually removed

- Relevant Issues : (none)
- Relevant PRs : (none)
- Type of issue :
  - [ ] Installation
  - [ ] Font-related
  - [ ] Feature request
  - [x] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

**Comment by avdv** [comment]
I think there is nothing we can do to prevent this, since the error is thrown inside bundler, when we just call `require`. So colorls cannot be loaded, in this case.

**Comment by avdv** [comment]
This has been resolved upstream: Bundler version finder breaks when run in deleted current working dir · Issue #3087 · rubygems/rubygems
https://github.com/rubygems/rubygems/issues/3087

**Comment by cycle2zhou** [comment]
Unfortunately for you, I upgraded to the latest version of 1.4, and it seems that the deleted bug still exists。
![image](https://user-images.githubusercontent.com/33155330/81470252-705b6980-921c-11ea-84b8-45a69579c3c2.png)
![image](https://user-images.githubusercontent.com/33155330/81470258-73eef080-921c-11ea-88f2-da2af1de7a03.png)

**Comment by avdv** [comment]
Again, this is not a problem that can be fixed in colorls. I closed this issue because the bug was fixed elsewhere.

You have to upgrade RubyGems on your system to a version including the fix and it will work, also with earlier colorls versions.

**Comment by cycle2zhou** [comment]
Thank you for your reply. I have known the problem @avdv

**Comment by avdv** [comment]
Hi @cycle2zhou , I was thinking about this a bit more...

At first, it thought that this was failing before colorls even had a chance to intercept, but this is wrong since the exe script is called which then calls `require` where the exception is raised.

I am putting together a workaround, which I am hoping to release until tomorrow...

**Comment by cycle2zhou** [comment]
Hi @avdv 
If you can solve the problem by skipping the RubyGems version, it will be more convenient than upgrading the RubyGems version, because it costs more to upgrade the ruby version on macOS, and I hope you can find a better solution

**Comment by avdv** [comment]
@cycle2zhou version 1.4.1 is out, please check if it fixes the problem for you (I just tested on Linux) and report back if it does not.

**Comment by cycle2zhou** [comment]
@avdv 太棒了，经过我的测试问题已经解决，在目录被删除后能显示更人性化的提示了



在测试该问题的同时，我发现了另外的一处需要独立说明的地方，我们在更新colorls时，如文档所示：gem update colorls；但在macOS上，如我下图所示，它会提示我没有权限，最后我发现colols安装到了/usr/local/bin目录的下面，经过改善命令后可以正常执行，改善后的命令：sudo gem update colorls -n /usr/local/bin
![image](https://user-images.githubusercontent.com/33155330/81518433-9db92c00-9370-11ea-8519-35825fc29b8f.png)
![image](https://user-images.githubusercontent.com/33155330/81518436-a0b41c80-9370-11ea-9edc-c16c2e43366a.png)

**Comment by avdv** [comment]
I didn't really understand what you're writing, but I see that it also works for you now.

**Comment by cycle2zhou** [comment]
Hi @avdv  The directory deletion problem has been solved, the following is a small opinion, thank you for your answer
