### ISSUE TITLE
Icons are broken [WSL / Ubuntu]

### ISSUE THREAD

**Issue by AkimaLunar** [athityakumar/colorls#379]
### Description

Type of issue: **Font-related**

I have tried a bunch of different Nerd fonts to no avail. All the font icons work fine in the [Spaceship prompt](https://github.com/denysdovhan/spaceship-prompt), which makes me think it might be a **icon mapping** issue specific to my system (WSL2).

**System:** 
Windows 10 Pro 2004 19041.421
WSL2 Ubuntu 18.04.4 LTS
Hyper / VS Code

![image](https://user-images.githubusercontent.com/5331992/89690034-74019980-d8ba-11ea-8828-086bdb42d0e9.png)

**Comment by avdv** [comment]
Hi.

What version of colorls are you using? And what is the output of `locale`?

**Comment by pergpau** [comment]
Same issue and setup, on WSL2.

➜ colorls --version
1.4.2

➜ locale
LANG=en_US.UTF8
LANGUAGE=
LC_CTYPE="en_US.UTF8"
LC_NUMERIC="en_US.UTF8"
LC_TIME="en_US.UTF8"
LC_COLLATE="en_US.UTF8"
LC_MONETARY="en_US.UTF8"
LC_MESSAGES="en_US.UTF8"
LC_PAPER="en_US.UTF8"
LC_NAME="en_US.UTF8"
LC_ADDRESS="en_US.UTF8"
LC_TELEPHONE="en_US.UTF8"
LC_MEASUREMENT="en_US.UTF8"
LC_IDENTIFICATION="en_US.UTF8"
LC_ALL=

**Comment by avdv** [comment]
How did you configure `fontFamily` for Hyper, which nerd font did you install? Does colorls work in other terminal emulators?

**Comment by AkimaLunar** [comment]
Here is what I've got, @avdv. Thanks!

```
➜ colorls --version
1.4.2
```

```
➜ locale
LANG=C.UTF-8
LANGUAGE=
LC_CTYPE="C.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_PAPER="C.UTF-8"
LC_NAME="C.UTF-8"
LC_ADDRESS="C.UTF-8"
LC_TELEPHONE="C.UTF-8"
LC_MEASUREMENT="C.UTF-8"
LC_IDENTIFICATION="C.UTF-8"
LC_ALL=
```

(1) How did you configure fontFamily for Hyper, which nerd font did you install?
```
    // font family with optional fallbacks
    fontFamily: '"Source Code Pro for Powerline", monospace',
```

(2) Does colorls work in other terminal emulators?
- Doesn't work in Hyper.js
- Doesn't work in VS Code

**Comment by avdv** [comment]
> ```
>  // font family with optional fallbacks
>     fontFamily: '"Source Code Pro for Powerline", monospace',
> ```
This is not a Nerd font. The corresponding Nerd font is called "SauceCodePro Nerd Font" (renamed because of legal reasons), see [here](https://www.nerdfonts.com/font-downloads).

**Comment by AkimaLunar** [comment]
Thanks, @avdv! That was it! I thought Powerline and nerd font were the same thing 🤦‍♀️ Thanks for helping!

**Comment by avdv** [comment]
Closing, since this should be resolved.

**Comment by pergpau** [comment]
I still have the same problem with these font settings in Hyper. It works fine on my laptop with Ubuntu desktop.
 // font family with optional fallbacks
fontFamily: '"Fira Code", Menlo, "DejaVu Sans Mono", Consolas, "Lucida Console", monospace',

**Comment by avdv** [comment]
> I still have the same problem with these font settings in Hyper. It works fine on my laptop with Ubuntu desktop.
> // font family with optional fallbacks
> fontFamily: '"Fira Code", Menlo, "DejaVu Sans Mono", Consolas, "Lucida Console", monospace',

You need to install a Nerd Font first. Then you should add that font to the setting in hyper. All Nerd Fonts have "Nerd Font" in their name.

**Comment by pergpau** [comment]
Thanks, I got it fixed now!
It was a Nerd font downloaded from here https://www.nerdfonts.com/font-downloads but for some reason Fira Code wouldn't work. I switched to the one called FuraCoda and now it works :)

**Comment by bluebrown** [comment]
I dont get it to work either. I tried out a bunch of different fonts, they work via windows terminal partwise but not with the regular ubuntu terminal.

For example here I have set FiraCode NerdFont

![settings showing foracode nerdfont](https://user-images.githubusercontent.com/39703898/210101970-f1308bde-98bf-4b1f-8922-9345b598acac.png)

But In my terminal the smbol is not showing, only that question mark box:

![terminal with broken fonts](https://user-images.githubusercontent.com/39703898/210102021-9d1c2c4a-3455-4f42-8a4c-0f7d4b125e2b.png)

**Comment by otaolafranc** [comment]
Hello, I am having a similar issue? I am using WSL with ubuntu, and FiraCode, I followed this tutorial: [https://www.youtube.com/watch?v=2LEnBXH8xV0&t=2s](url)
The thing is that, I have two possibilities to open the linux terminal:

- right click, and 'Open in terminal' which will open the linux terminal in the root directory (not expected behavior, I explain at the end of the phrase) and the fonts and icons will work correctly. what is really annoying of this is that it opens the terminal in the root directory and not in the current directory where I did the right click
- shit+right click and 'Open linux shell here' which will open the linux terminal in the current folder (so correct behavior), the fonts and some icons will not load correctly.
here is an image if the difference in behavior:
![image](https://github.com/athityakumar/colorls/assets/44319721/5d5f65cb-8331-4c78-9558-188fc618a65f)
in my .bashrc I have added the following lines:

`export BREW_HOME="/home/linuxbrew/.linuxbrew/bin"`
`export PATH="$PATH:$BREW_HOME"`
`#eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"` I also tried with this line uncommented and the first two commented
`eval "$(oh-my-posh init bash --config $(brew --prefix oh-my-posh)/themes/unicorn.omp.json)"`

the fonts, I downloaded from: [https://www.nerdfonts.com/font-downloads](url) and also installed inside the linux terminal using `oh-my-posh font install` and selecting FiraCode
I would like to use the oh-my-posh as it makes the terminal really pretty, but in terms of usability I need to be able to open the terminal in the current folder :/
any helps with this issue?
thanks
