### ISSUE TITLE
List of issues that do not work like normal ls

### ISSUE THREAD

**Issue by KSXGitHub** [athityakumar/colorls#59]
There're some options that works on normal `/usr/bin/ls` but does not work or works differently in `colorls`. Here're some (there're more in [`man ls`](http://man7.org/linux/man-pages/man1/ls.1.html) but I couldn't list them all, so I just list things I needed most):

* [x] Support files
* [x] `-a` and `--all` should also list `.` and `..`
* [x] `-A` and `--almost-all` should list all files except `.` and `..`
* [x] `-l` should print a long list
* [x] `-lh` and `-l --human-readable` should print a long list with human readable file size (in B, KB, MB, etc.)

**Related:**
* https://github.com/athityakumar/colorls/issues/57
* https://github.com/athityakumar/colorls/issues/58

**Comment by avdv** [comment]
For me, `-lh` still does not work, it gets ignored and a short list is printed.

And `-l` already enables human readable file sizes, but that's OK for me.

**Comment by GladOSkar** [comment]
@avdv yes. Because why would you want them to not be human readable? Though, we could think about a `-B` flag like exa does it, that shows the filesize in Bytes

**Comment by athityakumar** [comment]
`-a` and -A` flags have been fixed by PR #75

**Comment by avdv** [comment]
The problem is still that the parsing of the flags does not support combining short flags together, such that `-lhA` has the same effect as `-l -h -A`.

Is there a reason to open code the option parsing, why aren't you using optparse instead?

**Comment by athityakumar** [comment]
@avdv - Let' continue that discussion on issue #74? Closing this issue now.
